### ISSUE TITLE
Chapter 4 Using Mock Data is missing insectData.json

### ISSUE THREAD

**Issue by polishninja** [PacktPublishing/SwiftUI-Cookbook-2nd-Edition-#1]
The file insectData.json is missing from the project.

**Comment by Maran9** [comment]
Hi 
The insectData.json file is present at this link:
https://github.com/PacktPublishing/SwiftUI-Cookbook-2nd-Edition/blob/6dfcc36e49050375aad02141775deef812648900/Resources/Chapter04/recipe6/insectData.json

**Comment by polishninja** [comment]
Hello,

I see that it is there. It is not in the project folder and the link in the xcode project is broken. That is where the confusion happened. 

Thanks.
